### ISSUE TITLE
Post install hook preventing installation

### ISSUE THREAD

**Issue by YoussefKababe** [dominique-mueller/notification-js#2]
The post install hook in the package.json file prevents installation of the package on systems that don't have grunt-cli preinstalled.

**Comment by itsdevdom** [comment]
Good point, never thought of that. I always used Bower to install my frontend dependencies.
**Thanks for opening this issue here!**

Fixed with commit bc3c963, release 1.1.1 (https://github.com/dominique-mueller/notification-js/releases/tag/1.1.1) with an updated NPM package is out now.

Could you please update this dependency and verify that it works fine now ?

**Comment by YoussefKababe** [comment]
Yep, it's working like a charm now. Thank you so much @dominique-mueller!
